#!/usr/bin/env python3
"""Train Random Forest model on SDN-level features (5 features).

Loads CSV generated by generate_sdn_dataset.py, trains RF with GridSearchCV,
and saves the model to models/rf_ddos_model.pkl.
"""

import argparse
import csv
import os
import sys
import time
import numpy as np
import joblib

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score,
)

from src.util_functions import SEED

DATA_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data", "processed", "sdn_training_data.csv"
)
MODELS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "models"
)

HYPERPARAMETERS = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
}


def load_csv(csv_path):
    """Load SDN dataset from CSV and return X, y."""
    X, y = [], []
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            X.append([
                float(row["APf"]),
                float(row["ABf"]),
                float(row["GDP"]),
                float(row["NFi"]),
                float(row["NSi"]),
            ])
            y.append(int(row["label"]))
    return np.array(X), np.array(y)


def main():
    parser = argparse.ArgumentParser(description="Train RF model on SDN features")
    parser.add_argument("--data", default=DATA_PATH, help="Path to CSV dataset")
    parser.add_argument("--output", default=None, help="Output model path")
    parser.add_argument("--cv", type=int, default=5, help="Cross-validation folds")
    parser.add_argument("--test-size", type=float, default=0.2, help="Test set ratio")
    args = parser.parse_args()

    if args.output:
        model_path = args.output
    else:
        os.makedirs(MODELS_DIR, exist_ok=True)
        model_path = os.path.join(MODELS_DIR, "rf_ddos_sdn_model.pkl")

    # Load data
    print(f"Loading data from {args.data}...")
    X, y = load_csv(args.data)
    print(f"Loaded {len(X)} samples, {len(np.unique(y))} classes")
    print(f"  DDoS: {np.sum(y == 1)} | Normal: {np.sum(y == 0)}")

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=SEED, stratify=y
    )
    print(f"\nTrain: {len(X_train)} | Test: {len(X_test)}")

    # GridSearchCV
    print("\n=== Training Random Forest with GridSearchCV ===")
    print(f"Hyperparameters: {HYPERPARAMETERS}")
    print(f"CV folds: {args.cv}")

    rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, class_weight="balanced")
    grid = GridSearchCV(
        rf, HYPERPARAMETERS, cv=args.cv,
        scoring="f1", refit=True, verbose=1, n_jobs=-1,
    )

    start = time.time()
    grid.fit(X_train, y_train)
    train_time = time.time() - start

    best_model = grid.best_estimator_
    best_params = grid.best_params_

    print(f"\nTraining completed in {train_time:.2f}s")
    print(f"Best parameters: {best_params}")
    print(f"Best CV F1: {grid.best_score_:.4f}")

    # Evaluate on test set
    y_pred = best_model.predict(X_test)
    y_proba = best_model.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_proba)
    cm = confusion_matrix(y_test, y_pred)

    print(f"\n=== Test Set Results ===")
    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-Score:  {f1:.4f}")
    print(f"ROC-AUC:   {roc_auc:.4f}")
    print(f"Confusion Matrix:\n{cm}")

    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0
    print(f"FPR: {fpr:.4f} | FNR: {fnr:.4f}")

    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Normal", "DDoS"]))

    # Feature importance
    print(f"\nFeature importance:")
    feature_names = ["APf", "ABf", "GDP", "NFi", "NSi"]
    for name, importance in sorted(
        zip(feature_names, best_model.feature_importances_),
        key=lambda x: x[1], reverse=True,
    ):
        print(f"  {name}: {importance:.4f}")

    # Save model
    joblib.dump(best_model, model_path)
    print(f"\nModel saved to: {model_path}")
    print(f"Model expects {best_model.n_features_in_} features: {feature_names}")


if __name__ == "__main__":
    main()
